server:
  rest_port: 8080
  xds_port: 18000
  host: "0.0.0.0"

envoy:
  config_dir: "./configs"
  admin_port: 9901

logging:
  level: "info"

load_balancing:
  envoy_version: "1.24"
  available_policies:
    - "ROUND_ROBIN"
    - "LEAST_REQUEST"
    - "RANDOM"
    - "RING_HASH"
  default_policy: "ROUND_ROBIN"