services:
  # Our control plane service
  control-plane:
    build: .
    ports:
      - "8080:8080"   # REST API
      - "18000:18000" # xDS gRPC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - test-network

  # Envoy proxy that will connect to our control plane
  envoy:
    image: envoyproxy/envoy:v1.24-latest
    ports:
      - "10000:10000"  # Envoy proxy port (for client requests)
      - "9901:9901"    # Envoy admin interface
    volumes:
      - ./tests/e2e/envoy-bootstrap.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      control-plane:
        condition: service_healthy
    networks:
      - test-network
    user: "1001:1001"  # Run as non-root user
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info", "--base-id", "1"]

  # Simple HTTP backend for testing routing
  test-backend:
    image: kennethreitz/httpbin
    ports:
      - "3000:80"  # Expose to host for direct testing
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status/200"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  test-network:
    driver: bridge