### Health Check
GET http://127.0.0.1:8080/health

### Create Cluster

# @name cluster
POST http://127.0.0.1:8080/clusters
Content-Type: application/json

{
  "name": "httpbin-service",
  "endpoints": [
    {
      "host": "httpbin.org",
      "port": 80
    }
  ],
  "lb_policy": "LEAST_REQUEST"
}

### Create Cluster Id
@clusterId = {{cluster.response.body.$.data}}

### Get Clusters
GET http://127.0.0.1:8080/clusters

### Update Cluster

PUT http://127.0.0.1:8080/clusters/lifecycle-test-cluster
Content-Type: application/json

{
  "endpoints": [
    {
      "host": "httpbin-2.org",
      "port": 80
    },{
      "host": "httpbin-2.org",
      "port": 80,
      "tls_enabled": true
    }
  ]
}

### Update Cluster

PUT http://127.0.0.1:8080/clusters/lifecycle-test-cluster
Content-Type: application/json

{
  "lb_policy": "ROUND_ROBIN"
}

### Update Cluster

PUT http://127.0.0.1:8080/clusters/lifecycle-test-cluster
Content-Type: application/json

{
  "name": "httpbin-service",
  "endpoints": [
    {
      "host": "httpbin-1.org",
      "port": 80
    },{
      "host": "httpbin-1.org",
      "port": 80,
      "tls_enabled": true
    }
  ],
  "lb_policy": "LEAST_REQUEST"
}

### Get Cluster
GET http://127.0.0.1:8080/clusters/{{clusterId}}


### Create Route

# @name route
POST http://127.0.0.1:8080/routes
Content-Type: application/json

{
  "path": "/status/200",
  "cluster_name": "{{clusterId}}",
  "prefix_rewrite": "/status/200"
}

@routeId = {{route.response.body.$.data}}

### Get Routes
GET http://127.0.0.1:8080/routes

### Get Route
GET http://127.0.0.1:8080/routes/{{routeId}}

### Generate envoy config
POST http://127.0.0.1:8080/generate-config
Content-Type: application/json

{
    "proxy_name": "envoy-proxy-1", 
    "proxy_port": 10000
}

### Make api call
GET http://localhost:10000/status/200

### Make api call
PUT http://localhost:10000/put

### Make api call
GET http://localhost:10000/v1/get

### Delete Route
DELETE  http://127.0.0.1:8080/routes/{{routeId}}

### Delete cluster
DELETE  http://127.0.0.1:8080/clusters/{{clusterId}}