# ===========================================
# CONTROL PLANE CONFIGURATION - E2E TESTING
# Settings for Docker Compose e2e testing environment
# ===========================================
control_plane:
  server:
    rest_port: 8080        # REST API port for cluster/route management
    xds_port: 18000        # xDS server port for Envoy connections
    host: "0.0.0.0"        # Control plane binding address
  tls:
    cert_path: "./certs/server.crt"    # TLS certificate file path
    key_path: "./certs/server.key"     # TLS private key file path
    enabled: false                      # Enable TLS for xDS server
  logging:
    level: "info"          # Control plane log level
  load_balancing:
    envoy_version: "1.24"
    available_policies:    # Policies our control plane supports
      - "ROUND_ROBIN"
      - "LEAST_REQUEST"
      - "RANDOM"
      - "RING_HASH"
    default_policy: "ROUND_ROBIN"  # Default when none specified

# ===========================================
# ENVOY CONFIGURATION GENERATION - E2E TESTING
# Settings used when generating Envoy config files for Docker
# ===========================================
envoy_generation:
  config_dir: "./configs"  # Where to write generated Envoy configs
  admin:
    host: "127.0.0.1"      # Envoy admin interface binding
    port: 9901             # Envoy admin interface port
  listener:
    binding_address: "0.0.0.0"  # Envoy proxy listener binding
    default_port: 10000          # Default Envoy proxy port
  cluster:
    connect_timeout_seconds: 5   # Cluster connection timeout
    discovery_type: "STRICT_DNS" # Cluster discovery type (STRICT_DNS, LOGICAL_DNS, etc.)
    dns_lookup_family: "V4_ONLY" # DNS lookup family (V4_ONLY, V6_ONLY, AUTO)
    default_protocol: "TCP"      # Default endpoint protocol (TCP, UDP)
  naming:
    listener_name: "listener_0"        # Envoy listener name
    virtual_host_name: "local_service" # Virtual host name
    route_config_name: "local_route"   # Route configuration name
    default_domains: ["*"]             # Default virtual host domains
  bootstrap:
    node_id: "envoy-test-node"         # Envoy node identifier
    node_cluster: "envoy-test-cluster" # Envoy node cluster name
    control_plane_host: "control-plane" # Control plane service name (Docker Compose)
    main_listener_name: "main_listener" # Main proxy listener name
    control_plane_cluster_name: "control_plane_cluster" # Static cluster name for control plane
  http_filters:
    stat_prefix: "ingress_http"        # HTTP connection manager statistics prefix
    router_filter_name: "envoy.filters.http.router" # HTTP router filter name
    hcm_filter_name: "envoy.filters.network.http_connection_manager" # HTTP connection manager filter name